# librairies

library(plyr)
library(dplyr)
library(shiny)
library(shinythemes)
library(DT)
library(ggplot2)
library(xts)
library(GetoptLong)
library(gdata)
library(VIM)
library(stringr)
library(dygraphs)
library(xts)
library(dplyr)
library(chron)
library(survival)
library(rsconnect)

install.packages("plyr")
install.packages("dplyr")
install.packages("shiny")
install.packages("shinythemes")
install.packages("DT")
install.packages("ggplot2")
install.packages("xts")
install.packages("GetoptLong")
install.packages("gdata")
install.packages("VIM")
install.packages("stringr")
install.packages("dygraphs")
install.packages("xts")
install.packages("dplyr")
install.packages("chron")
install.packages("survival")
install.packages("rsconnect")


