# librairies

library(VIM)
library(ggplot2)
library(reshape2)
library(dygraphs)
library(plyr)
library(dplyr)
library(stringr)
library(chron)
library(xts)
library(data.table)
library(tm)
library(gmodels)
library(nlme)
library(lattice)
library(lme4)
library(scales)
library(nnet)
library(gdata)
library(pROC)
library(lcmm)
library(sjPlot)
library(sjmisc)
library(randomForest)
library(caret)
library(neuralnet)
library(party)
library(e1071)
library(C50)
library(kernlab)
library(class)
library(doParallel)
library(parallel)
library(foreach)
library(ROCR)
library(gridExtra)
library(rpart)
library(forecast)
library(wavelets)


